name: Build & Deploy Eleventy Site

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Deployment mode'
        required: true
        default: 'release'
        type: choice
        options:
          - release     # Full site
          - wip         # Under construction
          - takedown    # Take down the site

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js with a specific version and cache npm dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Step 3: Install dependencies (skip for takedown)
      - name: Install dependencies
        if: ${{ github.event.inputs.mode != 'takedown' }}  # Only install if it's not takedown
        run: npm ci

      # Step 4: Build the site based on the mode (release, wip, or takedown)
      - name: Build site
        run: |
          if [ "${{ github.event.inputs.mode }}" = "wip" ]; then
            npm run build:wip  # Builds the site in wip mode
          elif [ "${{ github.event.inputs.mode }}" = "takedown" ]; then
            echo "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>Takedown</title><style>body { background-color: black; color: white; font-family: Arial, sans-serif; text-align: center; padding: 50px; }</style></head><body><h1>Nothing to see here...</h1></body></html>" > ./dist/index.html
          else
            npm run build:release  # Builds the full site in release mode
          fi

      # Step 5: Add CNAME for custom domain (always add CNAME)
      - name: Add CNAME for custom domain
        run: |
          echo 'www.codekitten.me' > ./dist/CNAME  # Replace with your domain

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Deploy from the dist folder
